# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

$script = <<SCRIPT
echo "Provision"
if [ ! -f /etc/apt/sources.list.d/modera.list ];
then
     echo "install key"
     apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 1B322208
     echo "deb http://ubuntu.dev.modera.org/debian trusty main" > /etc/apt/sources.list.d/modera.list
fi
apt-get update && apt-get install -y -o Dpkg::Options::=--force-confnew mcloud mcloud-full
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.synced_folder ".", "/projects"

  config.vm.network "private_network", ip: "192.168.70.2"

  config.vm.provision "shell", inline: $script
end
