#!/bin/bash

echo "interface=lo" > /etc/dnsmasq.conf
echo "interface=docker0" >> /etc/dnsmasq.conf
echo "server=/mcloud.lh/`/sbin/ifconfig docker0 | grep 'inet addr:' | cut -d: -f2| cut -d' ' -f1`#7053" >> /etc/dnsmasq.conf