# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mcloud.app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(default='My app', max_length=255, unique=True, verbose_name='Name')),
                ('path', models.CharField(max_length=255, verbose_name='Path')),
                ('env', models.CharField(blank=True, default='dev', max_length=10, null=True, verbose_name='Environment name')),
                ('source', mcloud.app.models.YamlFancyField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('host', models.CharField(blank=True, default='unix://var/run/docker.sock/', max_length=255, null=True, verbose_name='Host')),
                ('port', models.SmallIntegerField(blank=True, null=True, verbose_name='Port')),
                ('default', models.BooleanField(default=False)),
                ('local', models.BooleanField(default=True)),
                ('tls', models.BooleanField(default=False)),
                ('key', models.TextField(blank=True, null=True)),
                ('cert', models.TextField(blank=True, null=True)),
                ('ca', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Application')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='deployment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Deployment'),
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together=set([('name', 'app')]),
        ),
    ]
