# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_application_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='data',
            new_name='config',
        ),
    ]
